name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the tagged Docker image
        run: docker build . --file .build/Dockerfile --tag vasary/tac-admin:latest

      - name: Push the latest Docker image
        run: docker push vasary/tac-admin:admin
