name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master

      - name: Installing project dependencies
        run: npm install

      - name: Building the project
        run: npm run build

      - name: Packing
        run: tar -czvf artifact.tar.gz ./dist

      - name: Uploading package
        uses: actions/upload-artifact@master
        with:
          name: artifact
          path: artifact.tar.gz
          retention-days: 1
